spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/doctor-of-personal-animals/dopa-config.git
          #username:
          #password:
          search-paths:
  application:
    name: sc-config-git
server:
    port: 9090